### ISSUE TITLE
klipper-configs file will need to be updated due to recently deprecated options in Klipper

### ISSUE THREAD

**Issue by TheTinkeringSquid** [teachingtechYT/klipper-configs#1]
As per the Klipper changelog (https://github.com/Klipper3d/klipper/blob/master/docs/Config_Changes.md), several options/features have been removed.

"20211102: Several deprecated features have been removed. The stepper step_distance option has been removed (deprecated on 20201222). The rpi_temperature sensor alias has been removed (deprecated on 20210219). The mcu pin_map option has been removed (deprecated on 20210325). The gcode_macro default_parameter_<name> and macro access to command parameters other than via the params pseudo-variable has been removed (deprecated on 20210503). The heater pid_integral_max option has been removed (deprecated on 20210612)."

The most notable one is the pin_map option. I found your config file very useful, but I just wanted to let you know that Klipper no longer allows you to specify an arduino pinout. Thankfully, it's not that hard to make the required changes, so I will share them here when I am done.

**Comment by KrzysztofKam** [comment]
First of all I would like to thank You for an excellent video tutorial on klipperization of CR-10 max 3D printer.
It helped a lot and I have now CR-10 max fully operational.
Nevertheless I would like to point out that I ran into several problems while using the provided printer.cfg file.


  1. The command:
pin_map: arduino
  is not supporter by klipper any more
  Instead I had to paste the following aliases:
 # Arduino aliases for atmega2560/1280 (Arduino mega) boards
[board_pins arduino-mega]
aliases:
ar0=PE0, ar1=PE1, ar2=PE4, ar3=PE5, ar4=PG5,
ar5=PE3, ar6=PH3, ar7=PH4, ar8=PH5, ar9=PH6,
ar10=PB4, ar11=PB5, ar12=PB6, ar13=PB7, ar14=PJ1,
ar15=PJ0, ar16=PH1, ar17=PH0, ar18=PD3, ar19=PD2,
ar20=PD1, ar21=PD0, ar22=PA0, ar23=PA1, ar24=PA2,
ar25=PA3, ar26=PA4, ar27=PA5, ar28=PA6, ar29=PA7,
ar30=PC7, ar31=PC6, ar32=PC5, ar33=PC4, ar34=PC3,
ar35=PC2, ar36=PC1, ar37=PC0, ar38=PD7, ar39=PG2,
ar40=PG1, ar41=PG0, ar42=PL7, ar43=PL6, ar44=PL5,
ar45=PL4, ar46=PL3, ar47=PL2, ar48=PL1, ar49=PL0,
ar50=PB3, ar51=PB2, ar52=PB1, ar53=PB0, ar54=PF0,
ar55=PF1, ar56=PF2, ar57=PF3, ar58=PF4, ar59=PF5,
ar60=PF6, ar61=PF7, ar62=PK0, ar63=PK1, ar64=PK2,
ar65=PK3, ar66=PK4, ar67=PK5, ar68=PK6, ar69=PK7,
analog0=PF0, analog1=PF1, analog2=PF2, analog3=PF3, analog4=PF4,
analog5=PF5, analog6=PF6, analog7=PF7, analog8=PK0, analog9=PK1,
analog10=PK2, analog11=PK3, analog12=PK4, analog13=PK5, analog14=PK6,
analog15=PK7,
# Marlin adds these additional aliases
ml70=PG4, ml71=PG3, ml72=PJ2, ml73=PJ3, ml74=PJ7,
ml75=PJ4, ml76=PJ5, ml77=PJ6, ml78=PE2, ml79=PE6,
ml80=PE7, ml81=PD4, ml82=PD5, ml83=PD6, ml84=PH2,
ml85=PH7


  2. There is an error in Your printer.cfg in line 86 - the whole line (containing: "Rotation_Distance.md") needs to be removed


  3. I ran into some problems with BLTouch not extending from time to time
  and causing nozzle crash into the printer bed during mesh calibration routine.
  The solution for me (so far) was to add in [bltouch]:
stow_on_each_sample: False
  and changing z axis limit in [stepper_z]:
position_min: -0.1
  The first limits the number of extensions so a crash is less likely,
  the latter should prevent damage in case the BLTouch would fail again.


  4. Also I corrected offsets of BLTouch to:
x_offset: -27
y_offset: -3


  5. Since I have a standard CR-10 max extruder the dir_pin is reversed:
dir_pin: ar28
  instead of
dir_pin: !ar28


  6. Also the standard CR-10 max extruder rotation_distance is different:
rotation_distance: 22.8571
  instead of
rotation_distance: 7.824


Other than that the printer.cfg file You provided was a great help to start using klipper.

**Comment by TheTinkeringSquid** [comment]
As promised, here is my slightly modified config that I verified with my Ender 3 Pro with a BLTouch as the only HW modification. I am still figuring out multi-point mesh bed leveling. Currently, my BLTouch is sampling a single point in the center of the bed. Lastly, since this is semi-specific to my application, I figured I'd post it here as a text document rather than request a merge.

[Klipper-CrealityEnder3Pro-printer.txt](https://github.com/teachingtechYT/klipper-configs/files/7746232/Klipper-CrealityEnder3Pro-printer.txt)

**Comment by teachingtechYT** [comment]
Hi guys,
Firstly, sorry for the slow respomnse, I don't monitor this repo at all and stumbled upon this issue by chance. Thanks for the input and motivation to get me to update. Some notes:

- There are several printer configs here but I think the Creality 8 bit board based CR-10 Max config is what is being discussed.
- I have updated some parts in the past, like the changes in variables for macros, but have not updated here. The CR-10 Max config has now been updated with this and the change from pin_map. Thank you [KrzysztofKam] for the pin mappings, they saved me some time.
- My printer has a Henera which explains some of the variations in cnfig. i have added this information to the header.
- "Rotation_Distance.md" line must have been a copy and paste error publishing to GitHub, as it wasn';t in my actual Klipper config. Fixed now.
- I also experimented with BLtouch reliability and came to the same conclusion.
 
Thanks again to both of you :)

**Comment by Finnitio** [comment]
> 

Hey, I have some trouble getting a connection with the updatet printer.cfg and my standard cr10 max. Mainsail throws me:

`Internal error during connect: [Errno 19] No such device`

The Klipper LOG gives me:

`Extruder max_extrude_ratio=0.598682
mcu 'mcu': Starting serial connect
webhooks client 1943877568: New connection
webhooks client 1943877568: Client info {'program': 'Moonraker', 'version': 'v0.8.0-23-g18f5ff4'}
Loaded MCU 'mcu' 105 commands (v0.11.0-122-ge6ef48cd / gcc: (GCC) 5.4.0 binutils: (GNU Binutils) 2.26.20160125)
MCU 'mcu' config: ADC_MAX=1023 BUS_PINS_spi=PB3,PB2,PB1 BUS_PINS_twi=PD0,PD1 CLOCK_FREQ=16000000 MCU=atmega2560 PWM_MAX=255 RECEIVE_WINDOW=192 RESERVE_PINS_serial=PE0,PE1 SERIAL_BAUD=250000 STATS_SUMSQ_BASE=256
mcu 'EBB': Starting CAN connect
Created a socket
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 176, in _connect
    self.send_event("klippy:mcu_identify")
  File "/home/pi/klipper/klippy/klippy.py", line 263, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/pi/klipper/klippy/klippy.py", line 263, in <listcomp>
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/pi/klipper/klippy/mcu.py", line 792, in _mcu_identify
    self._serial.connect_canbus(self._serialport, nodeid,
  File "/home/pi/klipper/klippy/serialhdl.py", line 135, in connect_canbus
    bus = can.interface.Bus(channel=canbus_iface,
  File "/home/pi/klippy-env/lib/python3.9/site-packages/can/interface.py", line 127, in __new__
    return cls(channel, *args, **kwargs)
  File "/home/pi/klippy-env/lib/python3.9/site-packages/can/interfaces/socketcan/socketcan.py", line 594, in __init__
    bind_socket(self.socket, channel)
  File "/home/pi/klippy-env/lib/python3.9/site-packages/can/interfaces/socketcan/socketcan.py", line 459, in bind_socket
    sock.bind((channel,))
OSError: [Errno 19] No such device`

i assume it has something to do with

`mcu 'EBB': Starting CAN connect`

As there are EBB references in pinout I was wondering if you @KrzysztofKam could post your printer.cfg for further debugging.

Kind reagrds

Finn

**Comment by Finnitio** [comment]
To clear things up, I got everything working, one thing I would like to mention, is that the last  commit adds a second controller via can bus, that is why it is not directly working. So I recommend checking the version history and use the version before.
